=== ravendano014/DRES---Requirements-Engineering-Support/dtd/form.dtd
<!-- NOT UP TO DATE! -->
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by KrzysioK (PUT) -->
<!ELEMENT form (input*, field+)>
<!ATTLIST form
	name CDATA #REQUIRED
	updatetitle CDATA #REQUIRED
	inserttitle CDATA #REQUIRED
	updatebutton CDATA #REQUIRED
	insertbutton CDATA #REQUIRED
>
<!ELEMENT input EMPTY>
<!ATTLIST input
	parameter CDATA #REQUIRED
	source (GET | POST | COOKIE) #REQUIRED
	field CDATA #REQUIRED
>
<!ELEMENT field (choice*)>
<!ATTLIST field
	name CDATA #REQUIRED
	label CDATA #REQUIRED
	comment CDATA #IMPLIED
	help CDATA #IMPLIED
	pattern CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	control (textfield | textarea | combo | checkbox | radio | hidden | readonly) #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	renderer CDATA #IMPLIED
	default CDATA #IMPLIED
	binding CDATA #REQUIRED
>
<!ELEMENT choice EMPTY>
<!ATTLIST choice
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== ravendano014/DRES---Requirements-Engineering-Support/forms/Requirement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE form SYSTEM "dtd/form.dtd">
<form name="requirement">
	<field name="req_rid" label="Requirement ID" control="readonly" binding="/requirement/@id"/>
	<field name="req_date" label="Date" control="readonly" binding="/requirement/@date"/>
	<field name="req_name" label="Name" control="textfield" binding="/requirement/@name" width="50"/>
	<field name="req_priority" label="Priority" control="combo" binding="/requirement/@priority">
		<choice name="high" value="high"/>
		<choice name="medium" value="medium"/>
		<choice name="low" value="low"/>
		<choice name="very low" value="very low"/>
	</field>
	<field name="req_desc" label="Description" control="textarea" binding="/requirement/description" width="50" height="5"/>
	<field name="req_deleted" label="Deleted" control="checkbox" binding="/requirement/@deleted">
		<choice name="on" value="1"/>
		<choice name="off" value="0"/>
	</field>
</form>
